# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cc52189a837dae12c60a82549d1a760cb2933a6ff77471c70bd77c23cf19b51db420c8ef0b73e158a8f3f4eba64caa57c359873f9a7aef7b6afb0dacbaf50d9

test:
  secret_key_base: 449c47d72f9b21c9c5076dd5adfa0da69c42368fc612b37dc67356a15bc2b3f091ea3f3aa2c98b0dd04c6dc05e91ef1122742d633f47bf23aa3544238e7b100b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
